Make ci.yaml use go commands instead of Makefile so that exit codes are not swallowed up

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -34,10 +34,14 @@ jobs:
           go-version: '1.22.5'
 
       - name: Install dependencies
-        run: make install
+        run: go mod tidy
 
       - name: Lint codebase
-        run: make lint
+        run: | 
+          if gofmt -l .| read; then \
+            echo "Linting failed"; \
+            exit 1; \
+          fi
 
       - name: Run tests
-        run: make test
+        run: go test -v ./...
